"""AI writing detection service — powered by Sapling AI Detector API.

Sapling is a purpose-built AI text classifier. It returns a 0–1 probability
score (higher = more likely AI-generated) plus per-sentence scores.

API docs: https://sapling.ai/docs/api/detector/
Free tier: available, no credit card required — get key at sapling.ai/user/login

Set SAPLING_API_KEY in your .env file.
If the key is missing, the service returns a clearly labelled fallback
result rather than crashing the whole verify pipeline.
"""

from __future__ import annotations

import logging
import os

import httpx
from fastapi import HTTPException, status

from models.verify import AIWritingResult, FlaggedPassage

logger = logging.getLogger(__name__)

_SAPLING_URL = "https://api.sapling.ai/api/v1/aidetect"
_HTTP_TIMEOUT = 30.0


# ---------------------------------------------------------------------------
# Response mapping
# ---------------------------------------------------------------------------

def _map_verdict(score: float) -> str:
    """Map Sapling's 0–1 AI probability to our verdict enum."""
    if score < 0.2:
        return "likely_human"
    elif score < 0.65:
        return "uncertain"
    else:
        return "likely_ai"


def _build_indicators(score: float, sentence_scores: list[dict]) -> list[str]:
    """Build human-readable indicators from Sapling response."""
    indicators: list[str] = []

    if score >= 0.65:
        indicators.append(
            f"Sapling classifier: {round(score * 100)}% probability of being AI-generated"
        )
    elif score >= 0.2:
        indicators.append(
            f"Sapling classifier: {round(score * 100)}% probability of AI involvement"
        )
    else:
        indicators.append(
            f"Sapling classifier: {round(score * 100)}% AI probability — appears human-written"
        )

    high_prob = [s for s in sentence_scores if s.get("score", 0) > 0.85]
    if high_prob:
        indicators.append(
            f"{len(high_prob)} sentence(s) scored >85% AI-generated by Sapling"
        )

    return indicators


def _build_flagged_passages(sentence_scores: list[dict]) -> list[FlaggedPassage]:
    """Extract highest-probability sentences as flagged passages."""
    scored = [
        s for s in sentence_scores
        if isinstance(s.get("score"), (int, float)) and s.get("sentence")
    ]
    scored.sort(key=lambda s: s["score"], reverse=True)

    passages: list[FlaggedPassage] = []
    for s in scored[:5]:
        prob = float(s["score"])
        if prob < 0.5:
            continue

        text = s["sentence"][:200]
        severity = "high" if prob > 0.85 else "medium" if prob > 0.65 else "low"
        reason = f"Sapling scores this sentence {round(prob * 100)}% likely AI-generated"
        passages.append(FlaggedPassage(text=text, reason=reason, severity=severity))

    return passages


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


async def detect_ai_writing(draft: str) -> AIWritingResult:
    """Analyse *draft* using the Sapling AI Detector API.

    Returns an AIWritingResult with a 0–100 score, verdict, flagged passages,
    and indicators.

    If SAPLING_API_KEY is not set, returns a clearly labelled unavailable
    result so the rest of the verify pipeline still runs.

    Raises:
        HTTPException: on API errors (timeout, auth failure, rate limit).
    """
    api_key = os.getenv("SAPLING_API_KEY", "").strip()

    # ------------------------------------------------------------------
    # Graceful degradation if key not configured
    # ------------------------------------------------------------------
    if not api_key:
        logger.warning(
            "ai_detection_service: SAPLING_API_KEY not set — skipping AI detection"
        )
        return AIWritingResult(
            score=0.0,
            verdict="likely_human",
            flagged_passages=[],
            indicators=["AI detection unavailable — SAPLING_API_KEY not configured."],
            explanation=(
                "AI writing detection is not configured. "
                "Add a SAPLING_API_KEY to your environment variables to enable this feature. "
                "Get a free key at sapling.ai/user/login."
            ),
            disclaimer=(
                "AI detection was not performed. "
                "Set SAPLING_API_KEY to enable Sapling-powered AI writing analysis."
            ),
        )

    # ------------------------------------------------------------------
    # Truncate to a safe length (~5000 words)
    # ------------------------------------------------------------------
    words = draft.split()
    if len(words) > 5000:
        text_to_send = " ".join(words[:5000])
        truncated = True
    else:
        text_to_send = draft
        truncated = False

    # ------------------------------------------------------------------
    # Call Sapling API
    # Sapling uses key in the JSON body (not a header)
    # ------------------------------------------------------------------
    payload = {
        "key": api_key,
        "text": text_to_send,
    }

    try:
        async with httpx.AsyncClient(timeout=_HTTP_TIMEOUT) as client:
            response = await client.post(
                _SAPLING_URL,
                json=payload,
                headers={"Content-Type": "application/json"},
            )
    except httpx.TimeoutException as exc:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Sapling AI Detector timed out. Please try again.",
        ) from exc
    except httpx.RequestError as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Could not reach Sapling AI Detector API.",
        ) from exc

    if response.status_code == 401:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Sapling authentication failed — check your SAPLING_API_KEY.",
        )
    if response.status_code == 429:
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail="Sapling rate limit reached. Try again shortly.",
        )
    if response.status_code != 200:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Sapling API returned status {response.status_code}.",
        )

    try:
        data = response.json()
    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="Sapling returned invalid JSON.",
        ) from exc

    # ------------------------------------------------------------------
    # Parse Sapling response
    # Shape: { "score": float,
    #          "sentence_scores": [{"sentence": str, "score": float}, ...] }
    # ------------------------------------------------------------------
    raw_score = float(data.get("score", 0.0))
    sentence_scores = data.get("sentence_scores") or []

    score = round(raw_score * 100, 1)
    verdict = _map_verdict(raw_score)
    indicators = _build_indicators(raw_score, sentence_scores)
    flagged_passages = _build_flagged_passages(sentence_scores)

    truncation_note = (
        " Note: only the first 5,000 words were analysed."
        if truncated else ""
    )

    explanation = (
        f"Sapling AI Detector estimates a {round(raw_score * 100)}% probability "
        f"this text is AI-generated.{truncation_note}"
    )

    return AIWritingResult(
        score=score,
        verdict=verdict,
        flagged_passages=flagged_passages,
        indicators=indicators,
        explanation=explanation,
        disclaimer=(
            "Powered by Sapling AI Detector. Results reflect statistical patterns, "
            "not certainty. A high score does not prove AI authorship; a low score "
            "does not guarantee human authorship. Always review flagged passages in context."
        ),
    )
