"""Export service — generates a formatted .docx from a ResearchResponse.

Sections:
  1. Title page  — research topic + date + model metadata
  2. Abstract    — the executive summary
  3. Best Papers — each paper as a styled entry (bold title, muted meta line)
  4. Methodology Table — condensed table mirroring the frontend MethodologyTable
  5. Research Gaps — open_questions as a bullet list
  6. Literature Review — key_findings as numbered sections with headers
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Optional

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor

from models.research import ResearchResponse


# ---------------------------------------------------------------------------
# Colour palette
# ---------------------------------------------------------------------------

_NAVY = RGBColor(0x1E, 0x3A, 0x5F)      # section headings
_STEEL = RGBColor(0x1E, 0x40, 0x6A)     # sub-headings
_SLATE_500 = RGBColor(0x64, 0x74, 0x8B) # subtitle
_SLATE_400 = RGBColor(0x94, 0xA3, 0xB8) # muted / captions
_GREY_600 = RGBColor(0x52, 0x52, 0x52)  # body-level muted text
_DARK = RGBColor(0x1E, 0x1E, 0x1E)      # regular body


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _set_cell_bg(cell, hex_fill: str) -> None:
    """Set a table cell background colour (hex without #, e.g. 'E2E8F0')."""
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_fill)
    tc_pr.append(shd)


def _cell_font(cell, size_pt: int = 9, bold: bool = False,
               color: Optional[RGBColor] = None) -> None:
    """Apply font settings to every run in a cell."""
    for para in cell.paragraphs:
        for run in para.runs:
            run.font.size = Pt(size_pt)
            run.font.bold = bold
            if color:
                run.font.color.rgb = color


def _add_spacer(doc: Document, lines: int = 1) -> None:
    for _ in range(lines):
        doc.add_paragraph()


def _heading(doc: Document, text: str, level: int,
             color: RGBColor = _NAVY) -> None:
    h = doc.add_heading(text, level=level)
    for run in h.runs:
        run.font.color.rgb = color


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_docx(response: ResearchResponse) -> bytes:
    """Return .docx bytes for *response*."""

    doc = Document()

    # ── Page margins ──────────────────────────────────────────────────────────
    for sec in doc.sections:
        sec.top_margin = Inches(1)
        sec.bottom_margin = Inches(1)
        sec.left_margin = Inches(1.25)
        sec.right_margin = Inches(1.25)

    # ── Base font ─────────────────────────────────────────────────────────────
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    # =========================================================================
    # 1. TITLE PAGE
    # =========================================================================

    _add_spacer(doc, 3)

    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = title_p.add_run(response.topic)
    r.bold = True
    r.font.size = Pt(26)
    r.font.color.rgb = _NAVY

    _add_spacer(doc)

    sub_p = doc.add_paragraph()
    sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = sub_p.add_run("Research Intelligence Report")
    r.font.size = Pt(14)
    r.font.color.rgb = _SLATE_500

    _add_spacer(doc)

    # Date
    generated = response.metadata.generated_at
    date_str = (
        generated.strftime("%B %d, %Y")
        if generated
        else datetime.utcnow().strftime("%B %d, %Y")
    )
    date_p = doc.add_paragraph()
    date_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = date_p.add_run(date_str)
    r.font.size = Pt(11)
    r.font.color.rgb = _SLATE_400

    # Model/depth caption
    model_p = doc.add_paragraph()
    model_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = model_p.add_run(
        f"Generated by {response.metadata.model}  ·  {response.metadata.depth} depth"
    )
    r.font.size = Pt(9)
    r.font.color.rgb = _SLATE_400

    doc.add_page_break()

    # =========================================================================
    # 2. ABSTRACT
    # =========================================================================

    _heading(doc, "Abstract", level=1)
    p = doc.add_paragraph(response.summary)
    p.style = doc.styles["Normal"]
    _add_spacer(doc)

    # =========================================================================
    # 3. BEST PAPERS
    # =========================================================================

    doc.add_page_break()
    _heading(doc, "Best Papers", level=1)

    papers = response.papers or []
    if not papers:
        doc.add_paragraph("No papers available.")
    else:
        for paper in papers:
            # Bold title
            title_p = doc.add_paragraph()
            r = title_p.add_run(paper.title)
            r.bold = True
            r.font.size = Pt(11)

            # Meta line: year · authors (≤3) · venue · DOI · citations
            parts: list[str] = []
            if paper.year:
                parts.append(str(paper.year))
            if paper.authors:
                names = paper.authors[:3]
                suffix = " et al." if len(paper.authors) > 3 else ""
                parts.append(", ".join(names) + suffix)
            if paper.venue:
                parts.append(paper.venue)
            if paper.doi:
                parts.append(f"DOI: {paper.doi}")
            if paper.citation_count is not None:
                parts.append(f"{paper.citation_count:,} citations")

            meta_p = doc.add_paragraph()
            r = meta_p.add_run(" · ".join(parts))
            r.font.size = Pt(9)
            r.font.color.rgb = _GREY_600

            # Abstract snippet (first 220 chars)
            if paper.abstract:
                snippet = paper.abstract[:220]
                if len(paper.abstract) > 220:
                    snippet += "…"
                abs_p = doc.add_paragraph(snippet)
                for run in abs_p.runs:
                    run.font.size = Pt(10)
                    run.font.color.rgb = _GREY_600

            _add_spacer(doc)

    # =========================================================================
    # 4. METHODOLOGY TABLE
    # =========================================================================

    doc.add_page_break()
    _heading(doc, "Methodology Overview", level=1)

    if papers:
        tbl = doc.add_table(rows=1, cols=4)
        tbl.style = "Table Grid"

        # Header row
        hdr = tbl.rows[0].cells
        for i, label in enumerate(("Paper", "Venue / Study Type", "Approach", "Outcome")):
            hdr[i].text = label
            _set_cell_bg(hdr[i], "1E3A5F")
            _cell_font(hdr[i], size_pt=10, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF))

        for paper in papers[:10]:
            first = paper.authors[0] if paper.authors else None
            last_name = first.split()[-1] if first else None
            label = (
                f"{last_name}, {paper.year}"
                if last_name and paper.year
                else paper.title[:40]
            )
            approach = (
                (paper.abstract[:90] + "…") if paper.abstract else "—"
            )

            row = tbl.add_row()
            row.cells[0].text = label
            row.cells[1].text = paper.venue or "—"
            row.cells[2].text = approach
            row.cells[3].text = paper.title[:60]
            for cell in row.cells:
                _cell_font(cell, size_pt=9)

    else:
        doc.add_paragraph("No methodology data available.")

    _add_spacer(doc)

    # =========================================================================
    # 5. RESEARCH GAPS & OPEN QUESTIONS
    # =========================================================================

    doc.add_page_break()
    _heading(doc, "Research Gaps & Open Questions", level=1)

    questions = response.open_questions or []
    if questions:
        for q in questions:
            bullet = doc.add_paragraph(style="List Bullet")
            bullet.add_run(q)
    else:
        doc.add_paragraph("No open questions identified.")

    _add_spacer(doc)

    # =========================================================================
    # 6. LITERATURE REVIEW
    # =========================================================================

    doc.add_page_break()
    _heading(doc, "Literature Review", level=1)

    findings = response.key_findings or []
    if findings:
        for idx, finding in enumerate(findings, start=1):
            # Section sub-heading: numbered claim
            _heading(doc, f"{idx}. {finding.claim}", level=2, color=_STEEL)

            # Evidence body
            doc.add_paragraph(finding.evidence)

            # Confidence + source IDs caption
            caption_parts = [f"Confidence: {finding.confidence.upper()}"]
            if finding.source_ids:
                caption_parts.append("Sources: " + ", ".join(finding.source_ids))
            cap_p = doc.add_paragraph()
            r = cap_p.add_run("  ·  ".join(caption_parts))
            r.font.size = Pt(9)
            r.font.color.rgb = _SLATE_400

            _add_spacer(doc)
    else:
        doc.add_paragraph("No key findings available.")

    # =========================================================================
    # Serialise to bytes
    # =========================================================================

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()
